# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: OTSTask@2
  inputs:
    OTSService: 'OTS 10.5.3 SoFy'
    teamspace: 'Initial Team Space'
    project: 'Emerald'
    branch: 'DEV'
    repo: 'https://github.com/HCL-TECH-SOFTWARE/Emerald-One-Test-Studio-Tests.git'
    filePath: 'Emeral_API_GuestCheckout/Logical/EmeraldAPIs.scm/React Store.scm/Add To Cart.gts'
    azureServer: 'https://dev.azure.com/stuartwalker0167/OneTestIntegrationDemo'
    patToken: 't4hgurmort6kzr3c67lgmadief62xub3xslzxojgoygjy63owvsa'
    testPlanName: 'TestPlan1'
    testCaseName: 'Existing Customer Checkout Process'
#- task: OTSTask@2
#  inputs:
#    OTSService: 'OTS 10.5.3 SoFy'
#    teamspace: 'Initial Team Space'
#    project: 'Emerald'
#    branch: 'DEV'
#    repo: 'https://github.com/HCL-TECH-SOFTWARE/Emerald-One-Test-Studio-Tests.git'
#    filePath: 'Emerald-UI-Tests/Emerald/Login Add Item & Checkout.testsuite'
#    variables: 'hostname=commerce-preview.sbx0064.play.hclsofy.dev;port_num=443'
#    azureServer: 'https://dev.azure.com/stuartwalker0167/OneTestIntegrationDemo'
#    patToken: 'ahdyui6cpmq6cljhno3lrgbiw3r7qbhmvvq6s75fwch6sdvan72a'
#    testPlanName: 'TestPlan1'
#    testCaseName: 'Existing Customer Checkout Process'